site_name: OSG Collaboration Support
site_url: https://osg-htc.org/collaboration-support
repo_name: https://github.com/osg-htc/collaboration-support
theme:
  name: material
  features:
    - content.tabs.link

nav:
  - Home: 'index.md'
  - Current Collaborations:
    - Overview: 'projects/project-list.md'
    - REDTOP: 'projects/Redtop.md'
    - IceCube: 'projects/icecube.md'
    - IGWN: 'projects/igwn.md'
    - LSST: 'projects/lsst.md'
    - South Pole Telescope: 'projects/spt.md'
    - VERITAS: 'projects/veritas.md'
    - XENON: 'projects/xenon.md'
    - GLUEX: 'projects/gluex.md'
    - GLAS12: 'projects/clas12.md'
    - MOLLER: 'projects/moller.md'
    - EIC: 'projects/eic.md'
    - Snowmass: 'projects/snowmass.md'
    - KOTO: 'projects/koto.md'
  - Meeting/Call schedule: 'misc/meeting-schedule.md'

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - admonition
  - codehilite:
      guess_lang: False
  - toc:
      permalink: True
